### ISSUE TITLE
Is it possible to output the chk instead of a protected mpq (scx)?

### ISSUE THREAD

**Issue by Chromowolf** [armoha/euddraft#13]
The output of each euddraft project is a SCX that cannot be decompressed by mpqEditor (Ladik's MPQ Editor). I'm intereted in the file structure of the CHK made by euddraft. So I need the output to be something like "scenario.chk" instead of the protected mpq. How can I achieve this?

**Comment by armoha** [comment]
You can extract `scenario.chk` with `MPQ Editor` and analyze with Hex editors.

Turning off freeze protection by writting followings in euddraft settings file(.eds or .edd) will be simpler to view.
```
[freeze]
freeze: 0
```

**Comment by Chromowolf** [comment]
The MPQeditor cannot extract scenario.chk.
I'm using SCMD2020-06-24 and euddraft0.9.0.5
.eds:
```
[main]
input: in.scx
output: t.scx

[freeze]
freeze: 0
```
![pic](https://user-images.githubusercontent.com/37732663/99990645-0c327880-2def-11eb-9105-005c4da9b835.png)
![pic2](https://user-images.githubusercontent.com/37732663/99990708-1f454880-2def-11eb-8e54-2d1b002bcde6.png)

**Comment by armoha** [comment]
euddraft removes `(listfile)` so filename won't be shown (`FileXXXXXXX.XXX`). But it does not block you to extract any file.

Try checking additional options; Merged mode, Read-only, Force opening MPQ as v1. Try adding additional listfile which has `scenario.chk`, or just extract any file and rename to `scenario.chk`.

**Comment by Chromowolf** [comment]
Thank you. I extracted that File00000000.xxx and viewed it in a HexEditor. It's indeed a CHK file. 

Another question, why can't SCMD open any EUD map made by euddraft? Even though I could extract the CHK and view its content by HexEditor, the scmd could never open it. The SCMD console always shows the following error messages:
![02](https://user-images.githubusercontent.com/37732663/100377332-07b6cb80-304c-11eb-9d41-2caea37bf1c7.png)
Would you mind giving me a hint about the underlying mechanism? And is there a way to open the EUD map via SCMD?
PS: I know nothing about the procedure of how the starcraft or SCMD reads a chk

**Comment by armoha** [comment]
Because SCMD2 isn't perfect? ;p

euddraft remove sections unused to StarCraft and only needed for map editors.

Also all euddraft maps have 2 triggers in MRGN section (which is supposed to contain location coordinates, name string indexes, and low/mid/high ground/air flags). They are initialization triggers for triggers in STR(x) section. Unlike TRIG or STR, MRGN has fixed memory address (`0x58DC60`).

**Comment by Chromowolf** [comment]
Triggers could exist outside TRIG section? This really blows my mind. :o
I inspected the MRGN section of the CHK of one euddraft map (created using an empty map, without [freeze]):
![mrgn](https://user-images.githubusercontent.com/37732663/100429678-a08f2a80-30d0-11eb-8549-be7e10f64738.png)
The section has a length of 5100 bytes with all bytes being 0 (except for the "Anywhere" location). 5100-byte is exactly the space needed for 255 locations (20 bytes for each). I didn't find the "2 triggers".

**Comment by armoha** [comment]
It had had (source: https://github.com/phu54321/eudplib/blob/6cc98b609f1bb620e5adad97918dd2a0c390cd25/eudplib/maprw/injector/vectorReloc.py#L98 ) for a long time but removed since `euddraft 0.9.0.0` (2020. 08. 08) because STR(x) section has fixed memory address in StarCraft: Remastered so MRGN loop is no longer needed.

**Comment by Chromowolf** [comment]
Thanks
