### ISSUE TITLE
Maybe there is something wrong with the DisplayCText's length?

### ISSUE THREAD

**Issue by boermyth** [armoha/euddraft#2]
Hi Armoha, 

The 11-line is good, but I find some texts don't exist in map but exist in game (It didn't exist before). I don't know why, Maybe there is something wrong with the DisplayCText's length?

Such as the screenshot ( I don't know how to display the picture here). Thanks for your good job.

Screenshot: 
https://www.scrpg.info/data/attachment/forum/201911/13/045820n5zakk826f8ba88s.png
https://share.weiyun.com/5nftvaa

**Comment by armoha** [comment]
Can't open second link. Maybe blocked in here?

Since SC 1.23.1 patch broked string modification (2 months ago), we had to alternatively print text directly to screen, which is done in euddraft 0.8.7.8.
It didn't use `DisplayText` but mimicks by EUD. So several issues comes e.g. text disappears fast.

In latest SC 1.23.2 patch, string modification blocking bug is partially fixed.
Currently, `DisplayText` shows *last displayed contents* in a trigger cycle.
```js
tct.print("1111");  // => Display "1111"
tct.print("222");  // => Display "1111"
tct.print("33");  // => Display "1111"
```
It quite limits usage of `customText`; you should call `DisplayCText` up to once every trigger cycle. I think it would be inappropriate for most EUD Editor 2 users, so didn't roll back euddraft to use string modification method.

I suggests two alternatives.
- Use euddraft 0.8.7.7 if you can handle the limitation and use DisplayCText only once in a trigger cycle.
- Wait next StarCraft patch to solve this issue perfectly. [This issue is already addressed and example test map is filed to Blizzard.](https://us.forums.blizzard.com/en/starcraft/t/patch-1-23-2-notes/825/62)

**Comment by boermyth** [comment]
Thank you for your good job.

**Comment by armoha** [comment]
Hi, @boermyth Could you try `euddraft 0.8.9.9` to see whether this issue is solved?
https://github.com/armoha/euddraft/releases/tag/v0.8.9.9

**Comment by boermyth** [comment]
> Hi, @boermyth Could you try `euddraft 0.8.9.9` to see whether this issue is solved?
> https://github.com/armoha/euddraft/releases/tag/v0.8.9.9

Now 8.9.9 it's ok. Good job. Thank you!

By the way, 

1. Can the eud make the map display the big hit points‘ number  such as 100000 in game？
2. Can the eud make the Drone not to die after creating the building which likes Probe or SCV?

**Comment by armoha** [comment]
> Can the eud make the map display the big hit points‘ number such as 100000 in game？

No. It's not capable with EUD. You need SC modding.

> Can the eud make the Drone not to die after creating the building which likes Probe or SCV?
1. Changing appearance of Probe of SCV to Drone would be easiest way.
2. Changing Drone's buttonset and requirements, etc.
- Change Button Action from Morph Building to SCV/Probe's.
- Change Order Requirements to allow Drone for SCV/Probe's build order.
