### ISSUE TITLE
Seek help for a SC's map Locker project

### ISSUE THREAD

**Issue by boermyth** [armoha/euddraft#3]
Hi Armoha,
Glad to write to you. By the way, I need a powerful SC's map Locker project such as StarcraftMapLockerProject (**SMLP**) from your Korea, but it's a very pity that the maps by SMLP 2.4.0/2.5.0 can't be open in SC 64bit. So can you send me it's lastest version or recommend another one? Thank you so much.

**Comment by armoha** [comment]
euddraft has built-in [freeze] protection, which is enabled by default since 0.8.9.1.
By using EDD compile button in EUD Editor 2, you can see freeze protection is applied to your map.
I don't know whether it is possible to apply SMLP in freeze-protected map.

SMLP didn't get any updates for 2 years. Last update is 2.5.0 in 2017.12.10.
[Author blog link](https://blog.tkyuki.kr/62)

**Comment by boermyth** [comment]
thank you, freeze is a cool protecter.

**Comment by 3244542253** [comment]
![eud error](https://user-images.githubusercontent.com/72880215/96019305-effdfc00-0e7e-11eb-9f8c-3a00c23cfc92.jpg)
Hello! I use the StarCraft 1eud editor version 0.8.99, which can be selected and opened normally. However, I found that some engineering files can be saved, while others can't. the displayed error is shown in the figure. How to solve this problem?

**Comment by armoha** [comment]
@3244542253 Try latest euddraft (0.9.0.4)
