### ISSUE TITLE
How to judge which interface language the SCR uses？

### ISSUE THREAD

**Issue by boermyth** [armoha/euddraft#6]
Hi, armoha

Do you know how to judge which interface language the SCR uses in map? And it won't drop any player (it means data asynchronization). I jsut want to judge Unpurchased English,简体中文,繁体中文 and 한국어. It's very useful.

**Comment by armoha** [comment]
I have not tested for 简体中文, and 繁体中文. Which language player uses is in itself local, asynchronous data; SC:R don't store each player's locale to EUD accessible addresses. Desynchronization is not a problem at all in EUD, as you can use MSQC to share one's local data to everyone.

If you planned to make i18n map, I think making users to select language in map is more simple way to go, rather than trying to automatically detect user language.
