### ISSUE TITLE
Simplified Chinese text is printed incorrectly

### ISSUE THREAD

**Issue by boermyth** [armoha/euddraft#7]
Incompatible with Simplified Chinese (GB2312/UTF-8?) which can't appear in the game, But it would be compatible in the past. I guess there is something wrong with the DisplayCText.

**Comment by armoha** [comment]
Well I have no problem printing Simplified Chinese. ([Screenshot](https://imgur.com/5VImzaV))
Do you get latest EUD Editor 2? EUD Editor 2 0.17.9.1 is needed for CText in StarCraft: Remastered 1.23.1 patch. (I made a EUD Editor 2 fork for supporting these.)
You can download latest EUD Editor 2 in [here(github link)](https://github.com/armoha/EUDEditor/blob/master/version/EUD%20Editor2%200.17.9.1.zip).

**Comment by armoha** [comment]
@boermyth Since current starcraft patch(1.23.1), modifying string is broken. I already reported this issue in [this forum post](https://us.forums.blizzard.com/en/starcraft/t/eud-string-modification-broken-in-1-23-1/645). Blizzard fixed it and the fix will ship in next version soon.

Until then, we should use alternatives by overwriting text on screen. For end users, update euddraft and EUD Editor 2, and recompile to make it work. EUD Editor 2 autoupdate does not work, so you should download and update to 0.17.9.1 manually.

**Comment by boermyth** [comment]
> @boermyth Since current starcraft patch(1.23.1), modifying string is broken. I already reported this issue in [this forum post](https://us.forums.blizzard.com/en/starcraft/t/eud-string-modification-broken-in-1-23-1/645). Blizzard fixed it and the fix will ship in next version soon.
> 
> Until then, we should use alternatives by overwriting text on screen. For end users, update euddraft and EUD Editor 2, and recompile to make it work. EUD Editor 2 autoupdate does not work, so you should download and update to 0.17.9.1 manually.

Thank you so much，I will have a try

**Comment by boermyth** [comment]
When I update EUD Editor2 0.17.9.1 to 8.6, it will downloading EUD Editor2.0.17.8.2, and where can I download the latest version?

**Comment by armoha** [comment]
> When I update EUD Editor2 0.17.9.1 to 8.6, it will downloading EUD Editor2.0.17.8.2, and where can I download the latest version?

https://github.com/armoha/EUDEditor/releases

**Comment by boermyth** [comment]
> > When I update EUD Editor2 0.17.9.1 to 8.6, it will downloading EUD Editor2.0.17.8.2, and where can I download the latest version?
> 
> https://github.com/armoha/EUDEditor/releases

Thank you so much， it's a  good job.
